[project]
name = "Instagram-Framework"
version = "0.1.1"
description = "A short description of the project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "instagrapi>=2.25.0",
    "numpy",
    "pandas>=1.0",
    "python-dotenv>=1.1.0"
]

[project.urls]
"Source" = "github.com"
